name: Publish NuGet to GitHub Packages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish NuGet Package

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Authenticate with GitHub Packages
        run: |
          dotnet nuget update source github \
          --source https://nuget.pkg.github.com/VuykoSheshych/index.json \
          --username VuykoSheshych \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"

      - name: Get Version
        run: |
          VERSION=$(gitversion /showvariable SemVer)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and publish
        run: |
          dotnet build -c Release
          dotnet pack -c Release /p:Version=$VERSION --output ./nupkg
          dotnet nuget push ./nupkg/*.nupkg --source github --skip-duplicate
